### ISSUE TITLE
Crashes when run with no arguments

### ISSUE THREAD

**Issue by iankronquist** [peterhuene/puppetcpp#58]
Fresh build off of master, OS X 10.10:
```
iankronquist@puppettop:(debug)(master) $ ./bin/puppetcpp 
Critical: unhandled exception: boost::bad_any_cast: failed conversion using boost::any_cast
Notice: compilation failed with 1 error and 0 warnings.
```
lldb is profoundly unhelpful.

**Comment by iankronquist** [comment]
Dies here:
https://github.com/peterhuene/puppetcpp/blob/master/lib/src/compiler/settings.cc#L113

**Comment by peterhuene** [comment]
Weird, log-level has a default value so it should be present.  I'll take a look later.
